apiVersion: apps/v1
kind: Deployment
metadata:
  name: development-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: dev-container
        image: us-east4-docker.pkg.dev/qwiklabs-gcp-03-35a3dd9b4f38/my-repository/hello-cloudbuild-dev:v1.0
        ports:
        - containerPort: 8080
